const products=['0,2 L','0,33 L','0,33 L EXCLUSIVE','0,5 L','1 L','1 L EXCLUSIVE','1,5 L','5 L','180 CC','250 CC','0,33 L CAM','0,75 L CAM','19 L PET','19 L PC','15 L CAM'], warehouses=['FABRİKA','SAKARYA','AVRUPA','ANADOLU','ANKARA'];let state={rows:[],history:[],summary:{}},draft={};const fmt=n=>new Intl.NumberFormat('tr-TR').format(n||0),esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;');
async function load(){let r=await fetch('/api/state',{cache:'no-store'});if(!r.ok)throw Error('Veri okunamadı');state=await r.json();renderAll()}
function get(p,w){return state.rows.find(x=>x.product===p&&x.warehouse===w)||{onHand:0,inTransit:0,minStock:0}}function val(p,w,k){return draft[p+'|'+w]?.[k]??get(p,w)[k]??0}
function dashboard(){let s=state.summary,t=s.totals||[],max=Math.max(1,...t.map(x=>x.value)),pt=s.productTotals||[],pm=Math.max(1,...pt.map(x=>x.value));document.querySelector('#dash').innerHTML=`<div class="cards"><div class="card hero"><small>GENEL TOPLAM</small><strong>${fmt(s.grand)}</strong><span>koli</span></div><div class="card"><small>DEPODAKİ STOK</small><strong>${fmt((s.grand||0)-(s.road||0))}</strong><span>tüm depolar</span></div><div class="card"><small>YOLDAKİ STOK</small><strong>${fmt(s.road)}</strong><span>tüm depolar</span></div><div class="card"><small>KRİTİK KALEM</small><strong>${fmt(s.critical)}</strong><span>minimum stok altı</span></div><div class="card"><small>SON KAYIT</small><strong style="font-size:18px">${s.updatedAt?new Date(s.updatedAt).toLocaleString('tr-TR'):'—'}</strong><span>veritabanı</span></div></div><div class="grid"><div class="panel"><h2>Depolara Göre Stok</h2><p>Depo + yoldaki toplam stok</p><div class="bars">${t.map(x=>`<div class="barwrap"><span>${fmt(x.value)}</span><div class="bar" style="height:${Math.max(2,x.value/max*220)}px"></div><b>${x.name}</b></div>`).join('')}</div></div><div class="panel products"><h2>En Yüksek Stoklu Ürünler</h2><p>Genel ürün toplamları</p>${pt.slice(0,8).map(x=>`<div class="row"><b>${x.name}</b><div class="track"><div class="fill" style="width:${x.value/pm*100}%"></div></div><span>${fmt(x.value)}</span></div>`).join('')||'<div class="empty">Henüz stok yok.</div>'}</div></div>`}

function factoryDashboard(){
  const rows=products.map(product=>{const x=get(product,'FABRİKA');return {product,onHand:Number(x.onHand)||0,inTransit:Number(x.inTransit)||0,total:(Number(x.onHand)||0)+(Number(x.inTransit)||0)}});
  const totalOnHand=rows.reduce((a,x)=>a+x.onHand,0), totalRoad=rows.reduce((a,x)=>a+x.inTransit,0), grand=totalOnHand+totalRoad;
  const stocked=rows.filter(x=>x.total>0).length, top=[...rows].sort((a,b)=>b.total-a.total)[0]||{product:'—',total:0};
  const max=Math.max(1,...rows.map(x=>x.total));
  document.querySelector('#factory').innerHTML=`<div class="factoryTitle"><div><span class="eyebrow">FABRİKA • CANLI STOK</span><h2>Fabrika Stok Dashboardu</h2><p>Stok Girişi ekranındaki FABRİKA verilerinden otomatik hesaplanır.</p></div><div class="factoryTotal">${fmt(grand)} <small>koli toplam</small></div></div><div class="cards factoryCards"><div class="card hero"><small>FABRİKA TOPLAM</small><strong>${fmt(grand)}</strong><span>depo + yolda</span></div><div class="card"><small>DEPODAKİ STOK</small><strong>${fmt(totalOnHand)}</strong><span>fiziki stok</span></div><div class="card"><small>YOLDA</small><strong>${fmt(totalRoad)}</strong><span>fabrikaya ait yoldaki</span></div><div class="card"><small>STOKLU ÜRÜN</small><strong>${fmt(stocked)}</strong><span>${products.length} ürün çeşidi</span></div><div class="card"><small>EN YÜKSEK ÜRÜN</small><strong class="topProduct">${esc(top.product)}</strong><span>${fmt(top.total)} koli</span></div></div><div class="grid factoryGrid"><div class="panel products factoryProducts"><h2>Fabrikada Hangi Üründen Ne Kadar Var?</h2><p>Ürün bazında depo stoku + yolda + toplam</p>${[...rows].sort((a,b)=>b.total-a.total).map(x=>`<div class="factoryRow"><b>${esc(x.product)}</b><div class="track"><div class="fill" style="width:${x.total/max*100}%"></div></div><span class="stockNum">${fmt(x.onHand)}</span><span class="roadNum">${fmt(x.inTransit)}</span><strong>${fmt(x.total)}</strong></div>`).join('')}<div class="factoryLegend"><span>Ürün</span><span>Grafik</span><span>Depo</span><span>Yolda</span><span>Toplam</span></div></div><div class="panel"><h2>Fabrika Ürün Dağılımı</h2><p>Toplam stoka göre ilk ürünler</p><div class="factoryRank">${[...rows].sort((a,b)=>b.total-a.total).slice(0,8).map((x,i)=>`<div class="rankItem"><i>${i+1}</i><div><b>${esc(x.product)}</b><small>Depo ${fmt(x.onHand)} • Yolda ${fmt(x.inTransit)}</small></div><strong>${fmt(x.total)}</strong></div>`).join('')}</div></div></div>`;
}
function stock(){document.querySelector('#stock').innerHTML=`<div class="panel tablePanel"><div class="tableHead"><div><h2>Stok Girişi</h2><p>Rakamları girin ve tek seferde kaydedin.</p></div><button class="primary" id="save">STOKLARI KAYDET</button></div><div class="scroll"><table><thead><tr><th rowspan="2">ÜRÜN</th>${warehouses.map(w=>`<th colspan="3">${w}</th>`).join('')}<th rowspan="2">GENEL TOPLAM</th></tr><tr>${warehouses.map(()=>'<th>Depo</th><th>Yolda</th><th>Toplam</th>').join('')}</tr></thead><tbody>${products.map(p=>`<tr><td class="prod">${p}</td>${warehouses.map(w=>`<td><input data-p="${p}" data-w="${w}" data-k="onHand" type="number" min="0" value="${val(p,w,'onHand')||''}"></td><td><input data-p="${p}" data-w="${w}" data-k="inTransit" type="number" min="0" value="${val(p,w,'inTransit')||''}"></td><td class="sum" data-sum="${p}|${w}">${fmt(val(p,w,'onHand')+val(p,w,'inTransit'))}</td>`).join('')}<td class="grand" data-grand="${p}">${fmt(warehouses.reduce((a,w)=>a+val(p,w,'onHand')+val(p,w,'inTransit'),0))}</td></tr>`).join('')}</tbody></table></div></div>`;document.querySelectorAll('#stock input').forEach(i=>i.oninput=()=>{let k=i.dataset.p+'|'+i.dataset.w;draft[k]=draft[k]||{onHand:get(i.dataset.p,i.dataset.w).onHand,inTransit:get(i.dataset.p,i.dataset.w).inTransit,minStock:get(i.dataset.p,i.dataset.w).minStock};draft[k][i.dataset.k]=Math.max(0,Number(i.value)||0);document.querySelector(`[data-sum="${CSS.escape(k)}"]`).textContent=fmt(val(i.dataset.p,i.dataset.w,'onHand')+val(i.dataset.p,i.dataset.w,'inTransit'));document.querySelector(`[data-grand="${CSS.escape(i.dataset.p)}"]`).textContent=fmt(warehouses.reduce((a,w)=>a+val(i.dataset.p,w,'onHand')+val(i.dataset.p,w,'inTransit'),0))});document.querySelector('#save').onclick=save}
async function save(){let items=products.flatMap(p=>warehouses.map(w=>({product:p,warehouse:w,onHand:val(p,w,'onHand'),inTransit:val(p,w,'inTransit'),minStock:val(p,w,'minStock')})));let m=document.querySelector('#msg');m.textContent='Kaydediliyor…';let r=await fetch('/api/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items})});if(!r.ok){m.textContent='Kayıt hatası';return}draft={};await load();m.textContent='✓ Kaydedildi';switchTab('dash');setTimeout(()=>m.textContent='',2500)}
function critical(){let rs=state.rows;document.querySelector('#critical').innerHTML=`<div class="panel tablePanel"><h2>Kritik Stok</h2><p>Minimum seviyenin altındaki ürünleri izleyin.</p><div class="scroll"><table><thead><tr><th>Ürün</th><th>Depo</th><th>Depo Stok</th><th>Yolda</th><th>Toplam</th><th>Minimum</th><th>Durum</th></tr></thead><tbody>${rs.map(x=>{let bad=x.minStock>0&&x.onHand+x.inTransit<x.minStock;return`<tr><td class="prod">${x.product}</td><td>${x.warehouse}</td><td>${fmt(x.onHand)}</td><td>${fmt(x.inTransit)}</td><td>${fmt(x.onHand+x.inTransit)}</td><td>${fmt(x.minStock)}</td><td><span class="badge ${bad?'bad':'ok'}">${bad?'KRİTİK':'NORMAL'}</span></td></tr>`}).join('')}</tbody></table></div></div>`}
function history(){document.querySelector('#history').innerHTML=`<div class="panel tablePanel"><h2>Hareket Geçmişi</h2><p>Son kayıtlar</p><div class="scroll"><table><thead><tr><th>Tarih</th><th>Ürün</th><th>Depo</th><th>Depo Stok</th><th>Yolda</th><th>Toplam</th></tr></thead><tbody>${state.history.map(x=>`<tr><td>${new Date(x.createdAt).toLocaleString('tr-TR')}</td><td class="prod">${x.product}</td><td>${x.warehouse}</td><td>${fmt(x.onHand)}</td><td>${fmt(x.inTransit)}</td><td>${fmt(x.onHand+x.inTransit)}</td></tr>`).join('')}</tbody></table></div></div>`}
function renderAll(){dashboard();factoryDashboard();stock();critical();history()}function switchTab(id){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('hide',x.id!==id));document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));if(id==='dash'||id==='factory')load().catch(()=>{})}document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));load().catch(e=>document.querySelector('#msg').textContent='Veri yükleme hatası');
