const http=require('http'),fs=require('fs'),path=require('path'),url=require('url');
const ROOT=__dirname, DATA=path.join(ROOT,'data','stocks.json'), HIST=path.join(ROOT,'data','history.json');
const products=['0,2 L','0,33 L','0,33 L EXCLUSIVE','0,5 L','1 L','1 L EXCLUSIVE','1,5 L','5 L','180 CC','250 CC','0,33 L CAM','0,75 L CAM','19 L PET','19 L PC','15 L CAM'];
const warehouses=['FABRİKA','SAKARYA','AVRUPA','ANADOLU','ANKARA'];
function init(){if(!fs.existsSync(DATA)) fs.writeFileSync(DATA,JSON.stringify(products.flatMap(product=>warehouses.map(warehouse=>({product,warehouse,onHand:0,inTransit:0,minStock:0,updatedAt:null}))),null,2));if(!fs.existsSync(HIST))fs.writeFileSync(HIST,'[]')}
function read(f){return JSON.parse(fs.readFileSync(f,'utf8'))} function write(f,d){fs.writeFileSync(f,JSON.stringify(d,null,2))}
function auth(req,res){const h=req.headers.authorization||'', ok='Basic '+Buffer.from('admin:Buzdagi2026!').toString('base64');if(h!==ok){res.writeHead(401,{'WWW-Authenticate':'Basic realm="Buzdagi Stok"'});res.end('Giris gerekli');return false}return true}
function json(res,obj,status=200){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(obj))}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>s+=c);req.on('end',()=>{try{resolve(JSON.parse(s||'{}'))}catch(e){reject(e)}})})}
function summary(rows){const totals=warehouses.map(name=>{let rs=rows.filter(x=>x.warehouse===name),onHand=rs.reduce((a,x)=>a+x.onHand,0),inTransit=rs.reduce((a,x)=>a+x.inTransit,0);return{name,onHand,inTransit,value:onHand+inTransit}});let pm={};rows.forEach(x=>pm[x.product]=(pm[x.product]||0)+x.onHand+x.inTransit);return{grand:totals.reduce((a,x)=>a+x.value,0),road:totals.reduce((a,x)=>a+x.inTransit,0),critical:rows.filter(x=>x.minStock>0&&x.onHand+x.inTransit<x.minStock).length,totals,productTotals:Object.entries(pm).map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value),updatedAt:rows.map(x=>x.updatedAt).filter(Boolean).sort().at(-1)||null}}
init();
const server=http.createServer(async(req,res)=>{if(!auth(req,res))return;let p=url.parse(req.url,true).pathname;
 try{
  if(p==='/api/state'&&req.method==='GET'){let rows=read(DATA);return json(res,{rows,history:read(HIST).slice(-300).reverse(),summary:summary(rows)})}
  if(p==='/api/save'&&req.method==='POST'){let b=await body(req);if(!Array.isArray(b.items))return json(res,{error:'Geçersiz veri'},400);let old=read(DATA), now=new Date().toISOString();let map=new Map(old.map(x=>[x.product+'|'+x.warehouse,x]));for(let i of b.items){let key=i.product+'|'+i.warehouse;if(!map.has(key))continue;let prev=map.get(key), next={...prev,onHand:Math.max(0,Math.round(Number(i.onHand)||0)),inTransit:Math.max(0,Math.round(Number(i.inTransit)||0)),minStock:Math.max(0,Math.round(Number(i.minStock)||0)),updatedAt:now};map.set(key,next)}let rows=[...map.values()];write(DATA,rows);let hist=read(HIST);for(let i of b.items){let x=rows.find(r=>r.product===i.product&&r.warehouse===i.warehouse);if(x)hist.push({...x,createdAt:now})}if(hist.length>10000)hist=hist.slice(-10000);write(HIST,hist);return json(res,{ok:true,summary:summary(rows)})}
  if(p==='/api/backup'){let rows=read(DATA), lines=['Ürün;Depo;Depo Stok;Yolda;Toplam;Minimum Stok;Son Güncelleme',...rows.map(x=>[x.product,x.warehouse,x.onHand,x.inTransit,x.onHand+x.inTransit,x.minStock,x.updatedAt||''].join(';'))];res.writeHead(200,{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':'attachment; filename="buzdagi-stok-yedek.csv"'});return res.end('\ufeff'+lines.join('\r\n'))}
  let file=p==='/'?'index.html':p.slice(1), fp=path.join(ROOT,'public',file);if(!fp.startsWith(path.join(ROOT,'public'))||!fs.existsSync(fp)){res.writeHead(404);return res.end('Bulunamadi')}let ext=path.extname(fp),ct=ext==='.css'?'text/css; charset=utf-8':ext==='.js'?'text/javascript; charset=utf-8':'text/html; charset=utf-8';res.writeHead(200,{'Content-Type':ct,'Cache-Control':'no-store'});fs.createReadStream(fp).pipe(res)
 }catch(e){console.error(e);json(res,{error:e.message},500)}});
let port=Number(process.env.PORT)||3100;server.listen(port,'0.0.0.0',()=>console.log(`BUZDAGI STOK HAZIR: http://localhost:${port}`));
